name: 'Testing Report Generator'
description: 'Create an issue including a testing report'
inputs:
  token:
    description: "Github repo access token"
    required: true
  repo_name:
    description: "The owner and repository name"
    required: true
    default: 'granluo/testing_report_generator'
  title:
    description: "Title of an issue"
    required: true
    default: 'Testing Report'
  label:
    description: "Label of an issue"
    required: true
    default: 'nightly-testing'
  skip_workflows:
    description: "Exclude testing workflows."
    required: false
    default: ''
  json_report:
    description: "Issue comment, including title, description, testing results"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'

