name: 'Testing Report Generator'
description: 'Create an issue including a testing report'
inputs:
  token:
    description: "GITHUB_TOKEN"
    required: true
  repo_name:
    description: "The owner and repository name"
    required: true
    default: 'granluo/testing_report_generator'
  title:
    description: "Title of an issue"
    required: true
    default: 'Testing Report'
  label:
    description: "Label of an issue"
    required: true
    default: 'nightly-testing'
  comment:
    description: "Issue comment, including title, description, testing results"
    required: true
    default: '{ "title": "Nightly testing report", "test_results": [ { "table_name": "11/16/2020 report", "colunm_names": [ "Workflow", "11/15" ], "contents": [ { "Workflow": "[zip1](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml)", "11/15": "[failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/365576620)" }, { "Workflow": "[zip2](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml)", "11/15": "failure" } ] }, { "table_name": "11/15/2020 report", "colunm_names": [ "Workflow", "11/14" ], "contents": [ { "Workflow": "[zip1](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml)", "11/14": "[failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/365576620)" }, { "11/14": "[failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/365576620)" } ] } ] }'
runs:
  using: 'docker'
  image: 'Dockerfile'

