name: 'Testing Report Generator'
description: 'Create an issue including a testing report'
inputs:
  token:
    description: "Github repo access token"
    required: true
  host_repo:
    description: "Name of repo that will post an issue"
    required: true
  target_repo:
    description: "Name of repo whose workflow will be read."
    required: false
  title:
    description: "Title of an issue"
    required: true
    default: 'Testing Report'
  label:
    description: "Label of an issue"
    required: true
    default: 'nightly-testing'
  skip_workflows:
    description: "Exclude testing workflows."
    required: false
    default: ''
  json_report:
    description: "Issue comment, including title, description, testing results"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'

