name: test_issue_generation_manually

on:
  workflow_dispatch:
    inputs:
      host_repo:
        description: "The owner and repository name"
        required: true
        default: 'granluo/testing_report_generator'
      target_repo:
        description: "Target repo of workflows"
        required: false
        default: 'firebase/firebase-ios-sdk'
      title:
        description: "Title of an issue"
        required: true
        default: 'Testing Report Manually'
      label:
        description: "Label of an issue"
        required: true
        default: 'manually-testing'
      json_report:
        description: "Issue comment, including title, description, testing results"
        required: false


jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - name: Test the action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        host_repo: ${{ github.event.inputs.host_repo }}
        target_repo: ${{ github.event.inputs.host_repo }}
        title: ${{ github.event.inputs.title }}
        label: ${{ github.event.inputs.label }}
        json_report: ${{ github.event.inputs.json_report }}
