name: test_issue_generation

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - name: Test the action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo_name: ${{ github.repository }}
        title: "Testing title"
        label: "nightly-testing"

      
