name: test_issue_generation

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - name: Test the action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo_name: ${{ env.GITHUB_REPOSITORY }}
        title: "Testing title"
        label: "nightly-testing"
        comment: '{ "title": "Nightly testing report", "test_results": [ { "table_name": "11/16/2020 report", "colunm_names": [ "Workflow", "11/15" ], "contents": [ { "Workflow": "[zip1](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml)", "11/15": "[failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/365576620)" }, { "Workflow": "[zip2](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml)", "11/15": "failure" } ] }, { "table_name": "11/15/2020 report", "colunm_names": [ "Workflow", "11/14" ], "contents": [ { "Workflow": "[zip1](https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml)", "11/14": "[failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/365576620)" }, { "11/14": "[failure](https://github.com/firebase/firebase-ios-sdk/actions/runs/365576620)" } ] } ] }'

      
