name: test_issue_generation

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - name: Test the action
      uses: ./
      with:
        title: "Testing title"

      
